import { Buffer } from 'buffer';
import { Address } from '@stellar/stellar-sdk';
import {
  AssembledTransaction,
  Client as ContractClient,
  ClientOptions as ContractClientOptions,
  MethodOptions,
  Result,
  Spec as ContractSpec,
} from '@stellar/stellar-sdk/contract';
import type {
  u32,
  i32,
  u64,
  i64,
  u128,
  i128,
  u256,
  i256,
  Option,
  Typepoint,
  Duration,
} from '@stellar/stellar-sdk/contract';
export * from '@stellar/stellar-sdk';
export * as contract from '@stellar/stellar-sdk/contract';
export * as rpc from '@stellar/stellar-sdk/rpc';

/* eslint-disable */
// This file is auto-generated by Soroban contract SDK
// Errors below are expected and cannot be fixed without modifying the SDK

if (typeof window !== 'undefined') {
  // @ts-ignore Buffer exists
  window.Buffer = window.Buffer || Buffer;
}

/**
 * Custom error types for the escrow contract
 */
export const EscrowError = {
  /**
   * Contract is already initialized
   */
  1: { message: 'AlreadyInitialized' },
  /**
   * Contract configuration not found
   */
  2: { message: 'ConfigNotInitialized' },
  /**
   * Unauthorized access
   */
  3: { message: 'Unauthorized' },
  /**
   * Escrow not found
   */
  4: { message: 'EscrowNotFound' },
  /**
   * Invalid amount (must be greater than 0)
   */
  5: { message: 'InvalidAmount' },
  /**
   * Invalid fee basis points (must be 0-10000)
   */
  6: { message: 'InvalidFeeBps' },
  /**
   * Invalid guarantee days (must be 1-36500)
   */
  7: { message: 'InvalidGuaranteeDays' },
  /**
   * Invalid product ID (cannot be empty)
   */
  8: { message: 'InvalidProductId' },
  /**
   * Escrow is not in active status
   */
  9: { message: 'EscrowNotActive' },
  /**
   * Guarantee period not expired
   */
  10: { message: 'GuaranteePeriodNotExpired' },
  /**
   * Guarantee period already expired
   */
  11: { message: 'GuaranteePeriodExpired' },
  /**
   * Fee amount exceeds escrow amount
   */
  12: { message: 'FeeExceedsAmount' },
  /**
   * Escrow is not in disputed status
   */
  13: { message: 'EscrowNotDisputed' },
  /**
   * Dispute already resolved
   */
  14: { message: 'DisputeAlreadyResolved' },
  /**
   * Both parties must agree on resolution
   */
  15: { message: 'BothPartiesMustAgree' },
  /**
   * Cannot resolve own dispute
   */
  16: { message: 'CannotResolveOwnDispute' },
};

/**
 * Event emitted when a new escrow is created
 */
export interface CreateEscrowEvent {
  amount: i128;
  asset: string;
  buyer: string;
  escrow_id: u64;
  fee_bps: u32;
  guarantee_days: u32;
  product_id: string;
  seller: string;
}

/**
 * Event emitted when escrow is disputed
 */
export interface DisputeEscrowEvent {
  as_buyer: boolean;
  disputed_by: string;
  escrow_id: u64;
}

/**
 * Event emitted when refund is issued to buyer
 */
export interface RequestRefundEvent {
  amount: i128;
  asset: string;
  buyer: string;
  escrow_id: u64;
}

/**
 * Event emitted when payment is released to seller
 */
export interface ReleasePaymentEvent {
  amount: i128;
  escrow_id: u64;
  fee: i128;
  seller: string;
  to_seller: i128;
}

/**
 * Event emitted when dispute is resolved
 */
export interface ResolveDisputeEvent {
  amount: i128;
  escrow_id: u64;
  resolution_type: boolean;
  resolved_in_favor_of: string;
}

/**
 * Event emitted when a party proposes a resolution to the dispute
 */
export interface ProposeResolutionEvent {
  escrow_id: u64;
  favor_seller: boolean;
  proposed_by: string;
}

/**
 * Contract configuration
 */
export interface Config {
  admin: string;
  collect_on_create: boolean;
}

/**
 * Storage keys for the escrow contract
 */
export type DataKey =
  | { tag: 'Escrow'; values: readonly [u64] }
  | { tag: 'Counter'; values: void }
  | { tag: 'Config'; values: void };

/**
 * Escrow data record
 */
export interface EscrowData {
  amount: i128;
  asset: string;
  buyer: string;
  buyer_resolution: u32;
  created_at: u64;
  disputed_by_buyer: boolean;
  fee_bps: u32;
  guarantee_days: u32;
  product_id: string;
  release_at: u64;
  seller: string;
  seller_resolution: u32;
  status: EscrowStatus;
}

/**
 * Status of an escrow
 */
export type EscrowStatus =
  | { tag: 'Active'; values: void }
  | { tag: 'Released'; values: void }
  | { tag: 'Refunded'; values: void }
  | { tag: 'Disputed'; values: void };

export interface Client {
  /**
   * Construct and simulate a prop_res transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Propõe uma resolução para a disputa (buyer ou seller)
   * as_buyer: true se está sendo chamado pelo buyer, false se pelo seller
   * favor_seller: true = favor seller (liberar pagamento), false = favor buyer (reembolso)
   */
  prop_res: (
    {
      escrow_id,
      as_buyer,
      favor_seller,
    }: { escrow_id: u64; as_buyer: boolean; favor_seller: boolean },
    options?: {
      /**
       * The fee to pay for the transaction. Default: BASE_FEE
       */
      fee?: number;

      /**
       * The maximum amount of time to wait for the transaction to complete. Default: DEFAULT_TIMEOUT
       */
      timeoutInSeconds?: number;

      /**
       * Whether to automatically simulate the transaction when constructing the AssembledTransaction. Default: true
       */
      simulate?: boolean;
    },
  ) => Promise<AssembledTransaction<null>>;

  /**
   * Construct and simulate a res_disp transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Resolve disputa (pode ser chamado por qualquer um após ambas as partes concordarem)
   */
  res_disp: (
    { escrow_id }: { escrow_id: u64 },
    options?: {
      /**
       * The fee to pay for the transaction. Default: BASE_FEE
       */
      fee?: number;

      /**
       * The maximum amount of time to wait for the transaction to complete. Default: DEFAULT_TIMEOUT
       */
      timeoutInSeconds?: number;

      /**
       * Whether to automatically simulate the transaction when constructing the AssembledTransaction. Default: true
       */
      simulate?: boolean;
    },
  ) => Promise<AssembledTransaction<null>>;

  /**
   * Construct and simulate a get_config transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  get_config: (options?: {
    /**
     * The fee to pay for the transaction. Default: BASE_FEE
     */
    fee?: number;

    /**
     * The maximum amount of time to wait for the transaction to complete. Default: DEFAULT_TIMEOUT
     */
    timeoutInSeconds?: number;

    /**
     * Whether to automatically simulate the transaction when constructing the AssembledTransaction. Default: true
     */
    simulate?: boolean;
  }) => Promise<AssembledTransaction<Config>>;

  /**
   * Construct and simulate a get_escrow transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  get_escrow: (
    { escrow_id }: { escrow_id: u64 },
    options?: {
      /**
       * The fee to pay for the transaction. Default: BASE_FEE
       */
      fee?: number;

      /**
       * The maximum amount of time to wait for the transaction to complete. Default: DEFAULT_TIMEOUT
       */
      timeoutInSeconds?: number;

      /**
       * Whether to automatically simulate the transaction when constructing the AssembledTransaction. Default: true
       */
      simulate?: boolean;
    },
  ) => Promise<AssembledTransaction<EscrowData>>;

  /**
   * Construct and simulate a create_escrow transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Cria escrow com período de garantia
   */
  create_escrow: (
    {
      buyer,
      seller,
      amount,
      asset,
      fee_bps,
      guarantee_days,
      product_id,
    }: {
      buyer: string;
      seller: string;
      amount: i128;
      asset: string;
      fee_bps: u32;
      guarantee_days: u32;
      product_id: string;
    },
    options?: {
      /**
       * The fee to pay for the transaction. Default: BASE_FEE
       */
      fee?: number;

      /**
       * The maximum amount of time to wait for the transaction to complete. Default: DEFAULT_TIMEOUT
       */
      timeoutInSeconds?: number;

      /**
       * Whether to automatically simulate the transaction when constructing the AssembledTransaction. Default: true
       */
      simulate?: boolean;
    },
  ) => Promise<AssembledTransaction<u64>>;

  /**
   * Construct and simulate a update_config transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Atualiza a configuração (somente admin atual)
   */
  update_config: (
    { new_admin, collect_on_create }: { new_admin: string; collect_on_create: boolean },
    options?: {
      /**
       * The fee to pay for the transaction. Default: BASE_FEE
       */
      fee?: number;

      /**
       * The maximum amount of time to wait for the transaction to complete. Default: DEFAULT_TIMEOUT
       */
      timeoutInSeconds?: number;

      /**
       * Whether to automatically simulate the transaction when constructing the AssembledTransaction. Default: true
       */
      simulate?: boolean;
    },
  ) => Promise<AssembledTransaction<null>>;

  /**
   * Construct and simulate a dispute_escrow transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Marca como disputado
   */
  dispute_escrow: (
    { escrow_id, as_buyer }: { escrow_id: u64; as_buyer: boolean },
    options?: {
      /**
       * The fee to pay for the transaction. Default: BASE_FEE
       */
      fee?: number;

      /**
       * The maximum amount of time to wait for the transaction to complete. Default: DEFAULT_TIMEOUT
       */
      timeoutInSeconds?: number;

      /**
       * Whether to automatically simulate the transaction when constructing the AssembledTransaction. Default: true
       */
      simulate?: boolean;
    },
  ) => Promise<AssembledTransaction<null>>;

  /**
   * Construct and simulate a request_refund transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Reembolso (apenas buyer e dentro do período de garantia)
   */
  request_refund: (
    { escrow_id }: { escrow_id: u64 },
    options?: {
      /**
       * The fee to pay for the transaction. Default: BASE_FEE
       */
      fee?: number;

      /**
       * The maximum amount of time to wait for the transaction to complete. Default: DEFAULT_TIMEOUT
       */
      timeoutInSeconds?: number;

      /**
       * Whether to automatically simulate the transaction when constructing the AssembledTransaction. Default: true
       */
      simulate?: boolean;
    },
  ) => Promise<AssembledTransaction<null>>;

  /**
   * Construct and simulate a release_payment transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Libera pagamento para o seller (após garantia ou pelo seller)
   */
  release_payment: (
    { escrow_id }: { escrow_id: u64 },
    options?: {
      /**
       * The fee to pay for the transaction. Default: BASE_FEE
       */
      fee?: number;

      /**
       * The maximum amount of time to wait for the transaction to complete. Default: DEFAULT_TIMEOUT
       */
      timeoutInSeconds?: number;

      /**
       * Whether to automatically simulate the transaction when constructing the AssembledTransaction. Default: true
       */
      simulate?: boolean;
    },
  ) => Promise<AssembledTransaction<null>>;

  /**
   * Construct and simulate a get_seller_escrows transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Lista todos os escrows de um seller
   */
  get_seller_escrows: (
    { seller }: { seller: string },
    options?: {
      /**
       * The fee to pay for the transaction. Default: BASE_FEE
       */
      fee?: number;

      /**
       * The maximum amount of time to wait for the transaction to complete. Default: DEFAULT_TIMEOUT
       */
      timeoutInSeconds?: number;

      /**
       * Whether to automatically simulate the transaction when constructing the AssembledTransaction. Default: true
       */
      simulate?: boolean;
    },
  ) => Promise<AssembledTransaction<Array<u64>>>;
}
export class Client extends ContractClient {
  static async deploy<T = Client>(
    /** Constructor/Initialization Args for the contract's `__constructor` method */
    { admin, collect_on_create }: { admin: string; collect_on_create: boolean },
    /** Options for initializing a Client as well as for calling a method, with extras specific to deploying. */
    options: MethodOptions &
      Omit<ContractClientOptions, 'contractId'> & {
        /** The hash of the Wasm blob, which must already be installed on-chain. */
        wasmHash: Buffer | string;
        /** Salt used to generate the contract's ID. Passed through to {@link Operation.createCustomContract}. Default: random. */
        salt?: Buffer | Uint8Array;
        /** The format used to decode `wasmHash`, if it's provided as a string. */
        format?: 'hex' | 'base64';
      },
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy({ admin, collect_on_create }, options);
  }
  constructor(public readonly options: ContractClientOptions) {
    super(
      new ContractSpec([
        'AAAAAAAAANZQcm9ww7VlIHVtYSByZXNvbHXDp8OjbyBwYXJhIGEgZGlzcHV0YSAoYnV5ZXIgb3Ugc2VsbGVyKQphc19idXllcjogdHJ1ZSBzZSBlc3TDoSBzZW5kbyBjaGFtYWRvIHBlbG8gYnV5ZXIsIGZhbHNlIHNlIHBlbG8gc2VsbGVyCmZhdm9yX3NlbGxlcjogdHJ1ZSA9IGZhdm9yIHNlbGxlciAobGliZXJhciBwYWdhbWVudG8pLCBmYWxzZSA9IGZhdm9yIGJ1eWVyIChyZWVtYm9sc28pAAAAAAAIcHJvcF9yZXMAAAADAAAAAAAAAAllc2Nyb3dfaWQAAAAAAAAGAAAAAAAAAAhhc19idXllcgAAAAEAAAAAAAAADGZhdm9yX3NlbGxlcgAAAAEAAAAA',
        'AAAAAAAAAFRSZXNvbHZlIGRpc3B1dGEgKHBvZGUgc2VyIGNoYW1hZG8gcG9yIHF1YWxxdWVyIHVtIGFww7NzIGFtYmFzIGFzIHBhcnRlcyBjb25jb3JkYXJlbSkAAAAIcmVzX2Rpc3AAAAABAAAAAAAAAAllc2Nyb3dfaWQAAAAAAAAGAAAAAA==',
        'AAAAAAAAAAAAAAAKZ2V0X2NvbmZpZwAAAAAAAAAAAAEAAAfQAAAABkNvbmZpZwAA',
        'AAAAAAAAAAAAAAAKZ2V0X2VzY3JvdwAAAAAAAQAAAAAAAAAJZXNjcm93X2lkAAAAAAAABgAAAAEAAAfQAAAACkVzY3Jvd0RhdGEAAA==',
        'AAAAAAAAACRDcmlhIGVzY3JvdyBjb20gcGVyw61vZG8gZGUgZ2FyYW50aWEAAAANY3JlYXRlX2VzY3JvdwAAAAAAAAcAAAAAAAAABWJ1eWVyAAAAAAAAEwAAAAAAAAAGc2VsbGVyAAAAAAATAAAAAAAAAAZhbW91bnQAAAAAAAsAAAAAAAAABWFzc2V0AAAAAAAAEwAAAAAAAAAHZmVlX2JwcwAAAAAEAAAAAAAAAA5ndWFyYW50ZWVfZGF5cwAAAAAABAAAAAAAAAAKcHJvZHVjdF9pZAAAAAAAEAAAAAEAAAAG',
        'AAAAAAAAAC9BdHVhbGl6YSBhIGNvbmZpZ3VyYcOnw6NvIChzb21lbnRlIGFkbWluIGF0dWFsKQAAAAANdXBkYXRlX2NvbmZpZwAAAAAAAAIAAAAAAAAACW5ld19hZG1pbgAAAAAAABMAAAAAAAAAEWNvbGxlY3Rfb25fY3JlYXRlAAAAAAAAAQAAAAA=',
        'AAAAAAAAAGBJbmljaWFsaXphIGEgY29uZmlndXJhw6fDo28gZG8gY29udHJhdG8KU29tZW50ZSBwb2RlIHNlciBjaGFtYWRvIDF4IG5vIGRlcGxveSAob3UgcXVhbmRvIHZhemlvKS4AAAANX19jb25zdHJ1Y3RvcgAAAAAAAAIAAAAAAAAABWFkbWluAAAAAAAAEwAAAAAAAAARY29sbGVjdF9vbl9jcmVhdGUAAAAAAAABAAAAAA==',
        'AAAAAAAAABRNYXJjYSBjb21vIGRpc3B1dGFkbwAAAA5kaXNwdXRlX2VzY3JvdwAAAAAAAgAAAAAAAAAJZXNjcm93X2lkAAAAAAAABgAAAAAAAAAIYXNfYnV5ZXIAAAABAAAAAA==',
        'AAAAAAAAADlSZWVtYm9sc28gKGFwZW5hcyBidXllciBlIGRlbnRybyBkbyBwZXLDrW9kbyBkZSBnYXJhbnRpYSkAAAAAAAAOcmVxdWVzdF9yZWZ1bmQAAAAAAAEAAAAAAAAACWVzY3Jvd19pZAAAAAAAAAYAAAAA',
        'AAAAAAAAAD5MaWJlcmEgcGFnYW1lbnRvIHBhcmEgbyBzZWxsZXIgKGFww7NzIGdhcmFudGlhIG91IHBlbG8gc2VsbGVyKQAAAAAAD3JlbGVhc2VfcGF5bWVudAAAAAABAAAAAAAAAAllc2Nyb3dfaWQAAAAAAAAGAAAAAA==',
        'AAAAAAAAACNMaXN0YSB0b2RvcyBvcyBlc2Nyb3dzIGRlIHVtIHNlbGxlcgAAAAASZ2V0X3NlbGxlcl9lc2Nyb3dzAAAAAAABAAAAAAAAAAZzZWxsZXIAAAAAABMAAAABAAAD6gAAAAY=',
        'AAAABAAAACpDdXN0b20gZXJyb3IgdHlwZXMgZm9yIHRoZSBlc2Nyb3cgY29udHJhY3QAAAAAAAAAAAALRXNjcm93RXJyb3IAAAAAEAAAAB9Db250cmFjdCBpcyBhbHJlYWR5IGluaXRpYWxpemVkAAAAABJBbHJlYWR5SW5pdGlhbGl6ZWQAAAAAAAEAAAAgQ29udHJhY3QgY29uZmlndXJhdGlvbiBub3QgZm91bmQAAAAUQ29uZmlnTm90SW5pdGlhbGl6ZWQAAAACAAAAE1VuYXV0aG9yaXplZCBhY2Nlc3MAAAAADFVuYXV0aG9yaXplZAAAAAMAAAAQRXNjcm93IG5vdCBmb3VuZAAAAA5Fc2Nyb3dOb3RGb3VuZAAAAAAABAAAACdJbnZhbGlkIGFtb3VudCAobXVzdCBiZSBncmVhdGVyIHRoYW4gMCkAAAAADUludmFsaWRBbW91bnQAAAAAAAAFAAAAKkludmFsaWQgZmVlIGJhc2lzIHBvaW50cyAobXVzdCBiZSAwLTEwMDAwKQAAAAAADUludmFsaWRGZWVCcHMAAAAAAAAGAAAAKEludmFsaWQgZ3VhcmFudGVlIGRheXMgKG11c3QgYmUgMS0zNjUwMCkAAAAUSW52YWxpZEd1YXJhbnRlZURheXMAAAAHAAAAJEludmFsaWQgcHJvZHVjdCBJRCAoY2Fubm90IGJlIGVtcHR5KQAAABBJbnZhbGlkUHJvZHVjdElkAAAACAAAAB5Fc2Nyb3cgaXMgbm90IGluIGFjdGl2ZSBzdGF0dXMAAAAAAA9Fc2Nyb3dOb3RBY3RpdmUAAAAACQAAABxHdWFyYW50ZWUgcGVyaW9kIG5vdCBleHBpcmVkAAAAGUd1YXJhbnRlZVBlcmlvZE5vdEV4cGlyZWQAAAAAAAAKAAAAIEd1YXJhbnRlZSBwZXJpb2QgYWxyZWFkeSBleHBpcmVkAAAAFkd1YXJhbnRlZVBlcmlvZEV4cGlyZWQAAAAAAAsAAAAgRmVlIGFtb3VudCBleGNlZWRzIGVzY3JvdyBhbW91bnQAAAAQRmVlRXhjZWVkc0Ftb3VudAAAAAwAAAAgRXNjcm93IGlzIG5vdCBpbiBkaXNwdXRlZCBzdGF0dXMAAAARRXNjcm93Tm90RGlzcHV0ZWQAAAAAAAANAAAAGERpc3B1dGUgYWxyZWFkeSByZXNvbHZlZAAAABZEaXNwdXRlQWxyZWFkeVJlc29sdmVkAAAAAAAOAAAAJUJvdGggcGFydGllcyBtdXN0IGFncmVlIG9uIHJlc29sdXRpb24AAAAAAAAUQm90aFBhcnRpZXNNdXN0QWdyZWUAAAAPAAAAGkNhbm5vdCByZXNvbHZlIG93biBkaXNwdXRlAAAAAAAXQ2Fubm90UmVzb2x2ZU93bkRpc3B1dGUAAAAAEA==',
        'AAAAAQAAACpFdmVudCBlbWl0dGVkIHdoZW4gYSBuZXcgZXNjcm93IGlzIGNyZWF0ZWQAAAAAAAAAAAARQ3JlYXRlRXNjcm93RXZlbnQAAAAAAAAIAAAAAAAAAAZhbW91bnQAAAAAAAsAAAAAAAAABWFzc2V0AAAAAAAAEwAAAAAAAAAFYnV5ZXIAAAAAAAATAAAAAAAAAAllc2Nyb3dfaWQAAAAAAAAGAAAAAAAAAAdmZWVfYnBzAAAAAAQAAAAAAAAADmd1YXJhbnRlZV9kYXlzAAAAAAAEAAAAAAAAAApwcm9kdWN0X2lkAAAAAAAQAAAAAAAAAAZzZWxsZXIAAAAAABM=',
        'AAAAAQAAACVFdmVudCBlbWl0dGVkIHdoZW4gZXNjcm93IGlzIGRpc3B1dGVkAAAAAAAAAAAAABJEaXNwdXRlRXNjcm93RXZlbnQAAAAAAAMAAAAAAAAACGFzX2J1eWVyAAAAAQAAAAAAAAALZGlzcHV0ZWRfYnkAAAAAEwAAAAAAAAAJZXNjcm93X2lkAAAAAAAABg==',
        'AAAAAQAAACxFdmVudCBlbWl0dGVkIHdoZW4gcmVmdW5kIGlzIGlzc3VlZCB0byBidXllcgAAAAAAAAASUmVxdWVzdFJlZnVuZEV2ZW50AAAAAAAEAAAAAAAAAAZhbW91bnQAAAAAAAsAAAAAAAAABWFzc2V0AAAAAAAAEwAAAAAAAAAFYnV5ZXIAAAAAAAATAAAAAAAAAAllc2Nyb3dfaWQAAAAAAAAG',
        'AAAAAQAAADBFdmVudCBlbWl0dGVkIHdoZW4gcGF5bWVudCBpcyByZWxlYXNlZCB0byBzZWxsZXIAAAAAAAAAE1JlbGVhc2VQYXltZW50RXZlbnQAAAAABQAAAAAAAAAGYW1vdW50AAAAAAALAAAAAAAAAAllc2Nyb3dfaWQAAAAAAAAGAAAAAAAAAANmZWUAAAAACwAAAAAAAAAGc2VsbGVyAAAAAAATAAAAAAAAAAl0b19zZWxsZXIAAAAAAAAL',
        'AAAAAQAAACZFdmVudCBlbWl0dGVkIHdoZW4gZGlzcHV0ZSBpcyByZXNvbHZlZAAAAAAAAAAAABNSZXNvbHZlRGlzcHV0ZUV2ZW50AAAAAAQAAAAAAAAABmFtb3VudAAAAAAACwAAAAAAAAAJZXNjcm93X2lkAAAAAAAABgAAAAAAAAAPcmVzb2x1dGlvbl90eXBlAAAAAAEAAAAAAAAAFHJlc29sdmVkX2luX2Zhdm9yX29mAAAAEw==',
        'AAAAAQAAAD9FdmVudCBlbWl0dGVkIHdoZW4gYSBwYXJ0eSBwcm9wb3NlcyBhIHJlc29sdXRpb24gdG8gdGhlIGRpc3B1dGUAAAAAAAAAABZQcm9wb3NlUmVzb2x1dGlvbkV2ZW50AAAAAAADAAAAAAAAAAllc2Nyb3dfaWQAAAAAAAAGAAAAAAAAAAxmYXZvcl9zZWxsZXIAAAABAAAAAAAAAAtwcm9wb3NlZF9ieQAAAAAT',
        'AAAAAQAAABZDb250cmFjdCBjb25maWd1cmF0aW9uAAAAAAAAAAAABkNvbmZpZwAAAAAAAgAAAAAAAAAFYWRtaW4AAAAAAAATAAAAAAAAABFjb2xsZWN0X29uX2NyZWF0ZQAAAAAAAAE=',
        'AAAAAgAAACRTdG9yYWdlIGtleXMgZm9yIHRoZSBlc2Nyb3cgY29udHJhY3QAAAAAAAAAB0RhdGFLZXkAAAAAAwAAAAEAAAAAAAAABkVzY3JvdwAAAAAAAQAAAAYAAAAAAAAAAAAAAAdDb3VudGVyAAAAAAAAAAAAAAAABkNvbmZpZwAA',
        'AAAAAQAAABJFc2Nyb3cgZGF0YSByZWNvcmQAAAAAAAAAAAAKRXNjcm93RGF0YQAAAAAADQAAAAAAAAAGYW1vdW50AAAAAAALAAAAAAAAAAVhc3NldAAAAAAAABMAAAAAAAAABWJ1eWVyAAAAAAAAEwAAAAAAAAAQYnV5ZXJfcmVzb2x1dGlvbgAAAAQAAAAAAAAACmNyZWF0ZWRfYXQAAAAAAAYAAAAAAAAAEWRpc3B1dGVkX2J5X2J1eWVyAAAAAAAAAQAAAAAAAAAHZmVlX2JwcwAAAAAEAAAAAAAAAA5ndWFyYW50ZWVfZGF5cwAAAAAABAAAAAAAAAAKcHJvZHVjdF9pZAAAAAAAEAAAAAAAAAAKcmVsZWFzZV9hdAAAAAAABgAAAAAAAAAGc2VsbGVyAAAAAAATAAAAAAAAABFzZWxsZXJfcmVzb2x1dGlvbgAAAAAAAAQAAAAAAAAABnN0YXR1cwAAAAAH0AAAAAxFc2Nyb3dTdGF0dXM=',
        'AAAAAgAAABNTdGF0dXMgb2YgYW4gZXNjcm93AAAAAAAAAAAMRXNjcm93U3RhdHVzAAAABAAAAAAAAAAAAAAABkFjdGl2ZQAAAAAAAAAAAAAAAAAIUmVsZWFzZWQAAAAAAAAAAAAAAAhSZWZ1bmRlZAAAAAAAAAAAAAAACERpc3B1dGVk',
      ]),
      options,
    );
  }
  public readonly fromJSON = {
    prop_res: this.txFromJSON<null>,
    res_disp: this.txFromJSON<null>,
    get_config: this.txFromJSON<Config>,
    get_escrow: this.txFromJSON<EscrowData>,
    create_escrow: this.txFromJSON<u64>,
    update_config: this.txFromJSON<null>,
    dispute_escrow: this.txFromJSON<null>,
    request_refund: this.txFromJSON<null>,
    release_payment: this.txFromJSON<null>,
    get_seller_escrows: this.txFromJSON<Array<u64>>,
  };
}
